### ISSUE TITLE
Real-time displaying data points?

### ISSUE THREAD

**Issue by hulinning2** [Code-Artist/MSChartExtension#15]
Hi, 
Can MSChartExtension support displaying data in real-time? Can we feed 1000 data points for every 100ms?
A max of 1000 data points in the chart can be display at at time.

Can it support displaying more than 1 series of data?

Thanks

**Comment by Code-Artist** [comment]
Hello @hulinning2 ,

MSChart alone with FastLine will be able to display 1000 data points without much problem.
With MSChartExtension, fast clear will help to speed up refresh rate.

You can try to simulate this behavior by ploting 10K data points with downsampling algorithm implemented in MSChartExtension by switching BufferedMode enabled and set DisplayDataSize to 1000. Then, Zoom in and scroll the chart.
Everytime you move the chart, 1000 data points is repainted.

More details here: [Implementation of Downsampling Algorithm in MSChart Extension](https://www.codearteng.com/2020/08/implementation-of-downsampling.html)

Yes, this tool support multiple series. 
For maximize performance, it's recommend to have good processor and SSD drive. Otherwise, the hardware might become your bottleneck on refreshing the data.

Hope my explanation helps.

Regards,
Code Artist.
